/**
 * recovery.ts — unified recovery + guard seam (ADR-0009).
 *
 * Two distinct hook points replaced the old inline "command failed → now what"
 * sprawl:
 *
 *   Guard (pre-execution)   — "should this run at all?"
 *     Budget cap (report-only / exceeded), pause, and command safety all gate
 *     execution. A guard outcome of "no" means the task never executes.
 *     cancel-report is a GUARD outcome, not a recovery.
 *
 *   RecoveryStrategy (post-execution)
 *     "now that this ran and did not pass, what next?"
 *     - failTerminal: mark failed + broadcast (WIRED)
 *     - healAndRetry: run healCommand, re-run phase command (WIRED via ADR-0011)
 *
 * healAndRetry is wired via execute-phases.ts (~L332): when a phase has a
 * healCommand, on verify failure it runs the healCommand then re-runs the
 * phase command on the WORKING TREE (no git worktree isolation). Exit-code
 * gated only (no LLM verifier); sets result.judgment = undefined on success.
 * The healCommand is a static YAML string from the plan file, not generated
 * by the LLM. Git-worktree isolation (src/worktree.ts) is defined but has
 * zero production callers — healing runs on the active working tree.
 *
 * @module recovery
 */

import type { PhaseDef, PhaseResult, Task } from "./types.js";
import type { TaskQueue } from "./task-queue.js";
import type { AuditViolation } from "./constitution.js";

// ── Guard (pre-execution) ─────────────────────────────────────────────────────

export interface GuardContext {
  baseDir: string;
  isPaused: () => Promise<boolean>;
  isSafeCommand: (command: string) => boolean;
}

export interface GuardDecision {
  /** false = do not run; the task is cancelled/reported, not executed. */
  run: boolean;
  /** Present only when run === false; human-readable cancel reason. */
  reason?: string;
}

/**
 * Pre-execution gate. Covers budget (via the caller-supplied budgetStatus),
 * pause, and command safety. A "no" decision means the task never executes —
 * which is why cancel-report belongs here, not in RecoveryStrategy.
 */
export const Guard = {
  async shouldRun(
    ctx: GuardContext,
    task: Task,
    budgetStatus: "ok" | "report_only" | "exceeded",
  ): Promise<GuardDecision> {
    if (budgetStatus === "exceeded") {
      return { run: false, reason: `budget exceeded, task skipped (${task.id})` };
    }
    if (budgetStatus === "report_only") {
      return { run: false, reason: `budget: report-only mode, task skipped (${task.id})` };
    }
    if (await ctx.isPaused()) {
      return { run: false, reason: "daemon paused, task skipped" };
    }
    if (!ctx.isSafeCommand(task.command)) {
      return { run: false, reason: "Command rejected: unsafe shell metacharacters detected" };
    }
    return { run: true };
  },
};

// ── RecoveryStrategy (post-execution) ─────────────────────────────────────────

export interface RecoveryContext {
  taskQueue: TaskQueue;
  broadcast: (type: string, data: unknown) => void;
  /** Injectable shell runner (healing re-runs a fix command). */
  runCommand?: (command: string, timeoutMs?: number) => Promise<{
    exitCode: number;
    stdout: string;
    stderr: string;
    durationMs: number;
  }>;
  getPlanDoc?: () => unknown;
  /** Post-heal constitution audit (T5): scans heal stdout/stderr for denylisted touches. */
  auditHeal?: (stdout: string, stderr: string) => AuditViolation[];
}

export interface HealConfig {
  healCommand: string;
  maxRetries: number;
}

export interface HealOutcome {
  healed: boolean;
  /** Denylisted touches detected in the heal output (T5 D6.5) — REJECT the phase. */
  auditViolations?: AuditViolation[];
}

export const RecoveryStrategy = {
  /**
   * Terminal failure: mark the task failed and broadcast completion.
   * This is the only wired recovery variant.
   */
  failTerminal(ctx: RecoveryContext, task: Task, error: string): void {
    ctx.taskQueue.fail(task.id, error);
    ctx.broadcast("task_completed", ctx.taskQueue.get(task.id));
  },

  /**
   * WIRED via execute-phases.ts (ADR-0011 heal seam). Runs healCommand up to
   * maxRetries times on the WORKING TREE (no git worktree isolation); on a heal
   * success, re-runs the phase command. If the verify passes, mutates `result`
   * in place to a passing state and returns { healed: true }.
   *
   * Exit-code gated only (no LLM verifier); sets result.judgment = undefined
   * on success. The healCommand is a static YAML string written in the plan
   * file, not generated by the LLM.
   */
  async healAndRetry(
    ctx: RecoveryContext,
    phase: PhaseDef,
    result: PhaseResult,
    heal: HealConfig,
  ): Promise<HealOutcome> {
    if (!ctx.runCommand) return { healed: false };
    for (let attempt = 1; attempt <= heal.maxRetries; attempt++) {
      const healResult = await ctx.runCommand(heal.healCommand, phase.timeoutMs);
      // T5 D6.5: the heal shares the post-hoc constitution audit. A denylisted
      // touch in its output REJECTS the phase — no further heal attempts.
      if (ctx.auditHeal) {
        const auditViolations = ctx.auditHeal(healResult.stdout, healResult.stderr);
        if (auditViolations.length > 0) {
          return { healed: false, auditViolations };
        }
      }
      if (healResult.exitCode !== 0) continue;
      const retry = await ctx.runCommand(phase.command ?? '', phase.timeoutMs);
      if (retry.exitCode === 0) {
        result.status = "pass";
        result.exitCode = retry.exitCode;
        result.stdout = retry.stdout;
        result.stderr = retry.stderr;
        result.durationMs = retry.durationMs;
        result.judgment = undefined;
        return { healed: true };
      }
    }
    return { healed: false };
  },
};
